### PR TITLE
Fix for #168

### LINKED ISSUE #168: [PE-D][Tester D] Course code only allows alphanumeric
In real usage, educators would likely teach multiple iterations of the same course over different semesters. 

Thus they would need to be able to name a course something like "AY2223S2-CS2103T" which is currently not supported.

It would be useful for users if the course code should support symbols.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: unfazing/ped#1

### PR DESCRIPTION
**Pull request by swxk19**
Also allows group/session/task names to have special characters 

Closes #168

### CODE REVIEW

**Comment by IsabelChong** [comment]
LGTM ☺️! Good job.

**Comment by tyx021** [comment]
Maybe have to let user know what is included in "special character", either add in error message / UG

**Comment by IsabelChong** [comment]
Would be better to add it inside the UG

**Comment by tyx021** [comment]
Added to the list of https://github.com/AY2223S2-CS2103T-T15-4/tp/issues/207 :)

**Pull request merged**
